export const REGISTER_USER = "REGISTER_USER";
export const ADD_JOB = "ADD_JOB";
export const REMOVE_JOB = "REMOVE_JOB";
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_CLEANER_PERSONAL_DATA = "UPDATE_CLEANER_PERSONAL_DATA";
export const UPDATE_CLEANER_DETAILS = "UPDATE_CLEANER_DETAILS";
export const UPDATE_CLEANER_DOCUMENTS_URL = "UPDATE_CLEANER_DOCUMENTS_URL";

